# Generated by Django 5.1.1 on 2024-09-05 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaborador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('dni', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99999999)])),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('departamento', models.TextField(max_length=100)),
                ('puesto', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'colaboradores',
                'ordering': ['nombre', 'apellido'],
                'unique_together': {('dni',)},
            },
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('tipo', models.TextField(max_length=100)),
                ('marca', models.TextField(max_length=100)),
                ('modelo', models.TextField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'equipos',
                'ordering': ['tipo', 'modelo'],
                'unique_together': {('numero_serie',)},
            },
        ),
    ]
