# Generated by Django 5.1 on 2024-09-07 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tecnico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('usuario', models.CharField(max_length=100, unique=True)),
                ('password', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'tecnicos',
                'ordering': ['nombre', 'apellido'],
                'unique_together': {('usuario',)},
            },
        ),
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_asignacion', models.DateTimeField()),
                ('estado', models.TextField(choices=[('asignado', 'Asignado'), ('disponible', 'Disponible')])),
                ('colaborador', models.ForeignKey(db_column='id_colaborador', on_delete=django.db.models.deletion.PROTECT, to='gestion.colaborador')),
                ('equipo', models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, to='gestion.equipo')),
                ('tecnico', models.ForeignKey(db_column='id_tecnico', on_delete=django.db.models.deletion.PROTECT, to='gestion.tecnico')),
            ],
            options={
                'db_table': 'asignaciones',
                'ordering': ['fecha_asignacion'],
            },
        ),
    ]
