# Generated by Django 5.1 on 2024-09-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_tecnico_asignacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.TextField(choices=[('disponible', 'Disponible'), ('asignado', 'Asignado')]),
        ),
    ]
