# Generated by Django 5.1 on 2024-09-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_asignacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='equipo',
            field=models.ForeignKey(db_column='id_equipo', on_delete=django.db.models.deletion.PROTECT, to='gestion.equipo', unique=True),
        ),
        migrations.AlterField(
            model_name='asignacion',
            name='estado',
            field=models.TextField(choices=[('asignado', 'Asignado'), ('disponible', 'Disponible')]),
        ),
    ]
